name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'  # Runs every day at 12:30 PM IST (07:00 AM UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: Submissions
          verbose: true
          commit-header: "[LeetCode Sync]"
